// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PuntoCuatroSQLite.Data;

#nullable disable

namespace PuntoCuatroSQLite.Migrations
{
    [DbContext(typeof(LaboratorioContext))]
    partial class LaboratorioContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.19");

            modelBuilder.Entity("PuntoCuatro.Models.Ensayo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("TEXT");

                    b.Property<int>("MuestraId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Resultado")
                        .HasColumnType("TEXT");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(80)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MuestraId");

                    b.ToTable("Ensayos");
                });

            modelBuilder.Entity("PuntoCuatro.Models.Muestra", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("FechaToma")
                        .HasColumnType("TEXT");

                    b.Property<string>("Matriz")
                        .HasColumnType("TEXT");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Muestras");
                });

            modelBuilder.Entity("PuntoCuatro.Models.Ensayo", b =>
                {
                    b.HasOne("PuntoCuatro.Models.Muestra", "Muestra")
                        .WithMany("Ensayos")
                        .HasForeignKey("MuestraId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Muestra");
                });

            modelBuilder.Entity("PuntoCuatro.Models.Muestra", b =>
                {
                    b.Navigation("Ensayos");
                });
#pragma warning restore 612, 618
        }
    }
}

